# 控制 monkey 发送消息的 Monkey 头
type= raw events
count= 10
speed= 1.0
start data >>
# 在此之下，编写 monkey 脚本命令

# 启动Activity
LaunchActivity(com.example.demo1,com.example.plokmju.testmutilecompile.MainActivity)
UserWait(800)
# 点击事件，点击坐标（120.270）
DispatchPointer(10,10,0,120,270,1,1,-1,1,1,0,0)
DispatchPointer(10,10,1,120,270,1,1,-1,1,1,0,0)
UserWait(500)
# 按键事件，键值4是返回
DispatchPress(KEYCODE_BACK)
UserWait(500)